version: '3.3'

services:
  db:
    image: mysql
    restart: unless-stopped
    container_name: mysqldb
    volumes:
      - mysqldb-volume:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    ports:
      - 8082:80
    environment:
      MYSQL_USERNAME: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
  
volumes:
  mysqldb-volume: